version: "3"
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile.django

  nginx:
    container_name: nginx
    ports:
      - 80:80
    build:
      context: .
      dockerfile: Dockerfile.nginx
    links:
      - app
    volumes:
      - ./staticfiles/:/var/html/static/
