name: GitHub Actions Demo
on: [push]
jobs:
  JOB_TO_TEST_PYTHON
  runs-on: ubuntu-latest
  steps:
   - name: Check out repository code
     uses: actions/checkout@v2
   - name: Run Scrips to test
     run: pip3 install -r  ./django-locallibrary-tutorial/requirements.txt
   - run: python3  ./django-locallibrary-tutorial/manage.py migrate
   - run: python3  ./django-locallibrary-tutorial/manage.py collectstatic
   - run: python3  ./django-locallibrary-tutorial/manage.py test
