name: GitHub Actions Demo
on: [push]
jobs:
 TEST_PYTHON:
  runs-on: ubuntu-20.04
  steps:
   - name: Check out repository code
     uses: actions/checkout@v2
   - run: ls -la
   - name: Run Scrips to test
     working-directory: ./django-locallibrary-tutorial
     run: pip3 install -r requirements.txt
   - run: python3 manage.py migrate
     working-directory: ./django-locallibrary-tutorial
   - run: python3 manage.py collectstatic
     working-directory: ./django-locallibrary-tutorial
   - run: python3 manage.py test
     working-directory: ./django-locallibrary-tutorial
